require("core.options")
require("core.keymaps")
require("core.misc")
require("core.autocommands")

require("plugins.lazy")
require("plugins.lualine")
require("plugins.neo-tree")
require("plugins.treesitter")
require("plugins.tmux-navigation")
require("plugins.telescope")
require("plugins.lsp")
require("plugins.cmp")
